### ISSUE TITLE
Notifications Are Not Displayed For Toot Replies

### ISSUE THREAD

**Issue by isosphere** [isosphere/mastodon#2]
### Steps to reproduce the problem

1. Toot a toot
2. Get a reply
3. You''ll never know that 2. happened, because it won't be in the web UI notifications tab
...

### Expected behaviour

A notification

### Actual behaviour

Zilch

### Mastodon instance

oceanplayground.social

### Mastodon version

ccfa3cce7

### Browser name and version

Firefox 115.11.0esr

### Operating system

Debian Bookworm

### Technical details

- systemctl shows `certbot`, `fail2ban`, and `mastodon-troubleshoot` in failed status.
- admin panel shows no issue (besides an update being available, unrelated to this AFAIK)
- glich-soc and mastodon upstream issues do not show recent issues with "notifications" `in:title`
- disk usage is healthy
- `dmesg` has complaints about `systemd-journald` regarding a data hash table, journal header limits exceeded
- `/var/log/nginx/error.log` looks fine

**Comment by isosphere** [comment]
This was reported by @jcolp and I've seen the truth of it! We merged with upstream at ccfa3cc and the user confirms that this timeframe seems right to them.

**Comment by isosphere** [comment]
# Investigation / Data Collection

There's a `notifications` table. What's in there?

```sql
SELECT MAX(created_at) FROM notifications
```

> "2024-05-24 18:12:08.939265"

Looks like the notifications are not being created in the first place. That's the date of our merge with upstream.

I think in ruby on rails speak, we need to look for `Notifications.new(` and find out why that isn't happening.

I've made a little bot that sends a message to me so I can test notifications.

**Comment by isosphere** [comment]
Rebooting the entire server seems to have addressed the issue, at least for the moment.

**Comment by jcolp** [comment]
I'm the user! It's me! I must admit it was kind of relaxing to not have notifications.

**Comment by isosphere** [comment]
This is happening again. Here are some coincident kernel log entries, which, AFAIK, should ordinarily be normal things to see:

```
Aug 02 03:09:25 oceanplayground systemd-journald[1619063]: Data hash table of /var/log/journal/2e857fa27d834506b9cbb3f992b4309e/system.journal has a fill level at 75.0 (174763 of 233016 items, 50331648 file size, 287 bytes per hash table item), suggesting rotation.
Aug 02 03:09:25 oceanplayground systemd-journald[1619063]: /var/log/journal/2e857fa27d834506b9cbb3f992b4309e/system.journal: Journal header limits reached or header out-of-date, rotating.
Aug 02 07:33:09 oceanplayground systemd-journald[1619063]: Data hash table of /var/log/journal/2e857fa27d834506b9cbb3f992b4309e/system.journal has a fill level at 75.0 (174763 of 233016 items, 50331648 file size, 287 bytes per hash table item), suggesting rotation.
Aug 02 07:33:09 oceanplayground systemd-journald[1619063]: /var/log/journal/2e857fa27d834506b9cbb3f992b4309e/system.journal: Journal header limits reached or header out-of-date, rotating.
Aug 02 11:56:54 oceanplayground systemd-journald[1619063]: Data hash table of /var/log/journal/2e857fa27d834506b9cbb3f992b4309e/system.journal has a fill level at 75.0 (174766 of 233016 items, 50331648 file size, 287 bytes per hash table item), suggesting rotation.
Aug 02 11:56:54 oceanplayground systemd-journald[1619063]: /var/log/journal/2e857fa27d834506b9cbb3f992b4309e/system.journal: Journal header limits reached or header out-of-date, rotating.
Aug 02 16:20:29 oceanplayground systemd-journald[1619063]: Data hash table of /var/log/journal/2e857fa27d834506b9cbb3f992b4309e/system.journal has a fill level at 75.0 (174763 of 233016 items, 50331648 file size, 287 bytes per hash table item), suggesting rotation.
Aug 02 16:20:29 oceanplayground systemd-journald[1619063]: /var/log/journal/2e857fa27d834506b9cbb3f992b4309e/system.journal: Journal header limits reached or header out-of-date, rotating.
```

I have rebooted the server. It fixed it.

Scheduling a weekly reboot on Sunday at 4 AM: done.
